### ISSUE TITLE
decode problem

### ISSUE THREAD

**Issue by Zakyr** [adeesha-savinda/huffman-encode-decode#1]
I have a text file which contains the string "the quick brown fox jumps over the lazy dog."

however when decoded it returns:
Decoded :
rodcpbo xo  svu exep  hlk mps over the lazy do
garbage input
![huffman](https://user-images.githubusercontent.com/50970544/104832896-b26e9c00-58cf-11eb-939c-65d81da50e5d.png)

**Comment by adeesha-savinda** [comment]
I will look into this

**Comment by ShyleshVR** [comment]
Is this issue cleared?

**Comment by Ketan33** [comment]
Yes, same issue

**Comment by adeesha-savinda** [comment]
Hi @Ketan33 and @ShyleshVR, did some changes. Could you please check if it works now?

**Comment by adeesha-savinda** [comment]
![image](https://github.com/adeesha-savinda/huffman-encode-decode/assets/8886211/3b013eb0-1512-4569-a439-525547f43d80)
Mine works fine. Please let me know if you face the issue still
